### ISSUE TITLE
loading terus

### ISSUE THREAD

**Issue by blackzero080** [moemoe89/autocomplete-city-rajaongkir-with-cache#1]
waktu ane klik cek 'calculate' loading terus gan, gak muncul2 ongkirnya
- key dah ane ganti
  ane pakai localhost
  autocomplete origin & destination dah bisa tapi waktu ane klik calculate loading terus, gak muncul2 ongkirnya
  kenapa tu gan?

**Comment by moemoe89** [comment]
coba pull lagi gan, sepertinya ada perubaha code dari rajaongkir.
Thx.
